/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LEDs.c
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.13, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings  :
**         Port name                   : M
**
**         Bit mask of the port        : $001F
**         Number of bits/pins         : 5
**         Single bit numbers          : 0 to 4
**         Values range                : 0 to 31
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTM       [$0250]
**         Port control register       : DDRM      [$0252]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    105  |   PM0_RxCAN0
**                    1      |    104  |   PM1_TxCAN0
**                    2      |    103  |   PM2_RxCAN1_RxCAN0_MISO0
**                    3      |    102  |   PM3_TxCAN1_TxCAN0_SS0
**                    4      |    101  |   PM4_RxCAN2_RxCAN0_RxCAN4_MOSI0
**             ----------------------------------------------------
**
**         Optimization for            : code size
**     Contents  :
**         GetDir - bool LEDs_GetDir(void);
**         GetVal - byte LEDs_GetVal(void);
**         PutVal - void LEDs_PutVal(byte Val);
**         GetBit - bool LEDs_GetBit(byte Bit);
**         PutBit - void LEDs_PutBit(byte Bit, bool Val);
**         SetBit - void LEDs_SetBit(byte Bit);
**         ClrBit - void LEDs_ClrBit(byte Bit);
**         NegBit - void LEDs_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE LEDs. */

#include "LEDs.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG LEDs_DATA             /* Select data segment "LEDs_DATA" */
#pragma CODE_SEG LEDs_CODE
#pragma CONST_SEG LEDs_CONST           /* Constant section for this module */
/*
** ===================================================================
**     Method      :  LEDs_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte LEDs_Table[5U] = {   /* Table of mask constants */
   0x01U, 0x02U, 0x04U, 0x08U, 0x10U
};

static byte LEDs_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<5U) ? LEDs_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  LEDs_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 31)
** ===================================================================
*/
byte LEDs_GetVal(void)
{
  return (byte)(getReg8(PTM) & 0x1FU); /* Return port data */
}

/*
** ===================================================================
**     Method      :  LEDs_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_PutVal(byte Val)
{
  Val &= 0x1FU;                        /* Mask output value */
  setReg8(PTM, (getReg8(PTM) & (byte)(~(byte)0x1FU)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  LEDs_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 4)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool LEDs_GetBit(byte Bit)
{
  byte const Mask = LEDs_GetMsk(Bit);  /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PTM) & Mask) == Mask)? 1U: 0U); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  LEDs_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 4)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_PutBit(byte Bit, bool Val)
{
  byte const Mask = LEDs_GetMsk(Bit);  /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTM, Mask);            /* [bit (Bit)]=0x01U */
  } else { /* !Val */
    clrReg8Bits(PTM, Mask);            /* [bit (Bit)]=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  LEDs_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 4)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_ClrBit(byte Bit)
{
  byte const Mask = LEDs_GetMsk(Bit);  /* Temporary variable - set bit mask */
  clrReg8Bits(PTM, Mask);              /* [bit (Bit)]=0x00U */
}

/*
** ===================================================================
**     Method      :  LEDs_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 4)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_SetBit(byte Bit)
{
  byte const Mask = LEDs_GetMsk(Bit);  /* Temporary variable - set bit mask */
  setReg8Bits(PTM, Mask);              /* [bit (Bit)]=0x01U */
}

/*
** ===================================================================
**     Method      :  LEDs_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_NegBit(byte Bit)
{
  byte const Mask = LEDs_GetMsk(Bit);  /* Temporary variable - set bit mask */
  invertReg8Bits(PTM, Mask);           /* [bit (Bit)]=invert */
}

/*
** ===================================================================
**     Method      :  LEDs_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool LEDs_GetDir(void)

**  This method is implemented as a macro. See LEDs.h file.  **
*/


/* END LEDs. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
