/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SevenSEG_Data.h
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : ByteIO
**     Version   : Component 02.058, Driver 03.15, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : A
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         8-bit data register         : PORTA     [$0000]
**         8-bit control register      : DDRA      [$0002]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    57   |   PA0
**                    1      |    58   |   PA1
**                    2      |    59   |   PA2
**                    3      |    60   |   PA3
**                    4      |    61   |   PA4
**                    5      |    62   |   PA5
**                    6      |    63   |   PA6
**                    7      |    64   |   PA7
**             ----------------------------------------------------
**     Contents  :
**         PutVal - void SevenSEG_Data_PutVal(byte Val);
**         NegBit - void SevenSEG_Data_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef SevenSEG_Data_H_
#define SevenSEG_Data_H_

/* MODULE SevenSEG_Data. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu.h"

#pragma CODE_SEG SevenSEG_Data_CODE
/*
** ===================================================================
**     Method      :  SevenSEG_Data_PutVal (component ByteIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
#define SevenSEG_Data_PutVal(Val) ( \
    (void)setReg8(PORTA, Val)          /* PA0-PA7=Val[bits 0-7] */ \
  )

/*
** ===================================================================
**     Method      :  SevenSEG_Data_NegBit (component ByteIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void SevenSEG_Data_NegBit(byte Bit);

#pragma CODE_SEG DEFAULT

/* END SevenSEG_Data. */
#endif /* #ifndef __SevenSEG_Data_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
