/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Encoder_F.c
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : PulseAccumulator
**     Version   : Component 01.185, Driver 01.19, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**     Settings  :
**             Pulse accumulator       : ECTPACNT23
**
**              Pulse accumulator      : Enabled
**              Events                 : Enabled
**              Overwrite mode         : Disabled
**
**         Timer registers
**              Counter                : ECT_PACN32 [$0062]
**              Hold                   : ECT_PA32H [$0072]
**              Mode                   : ECT_ICOVW [$006A]
**              Run                    : ECT_PACTL [$0060]
**              Prescaler              : ECT_PACTL [$0060]
**
**         User handling procedure     : not specified
**
**     Contents  :
**         Enable          - byte Encoder_F_Enable(void);
**         Disable         - byte Encoder_F_Disable(void);
**         ResetCounter    - void Encoder_F_ResetCounter(void);
**         GetCounterValue - Encoder_F_TCounterValue Encoder_F_GetCounterValue(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Encoder_F. */

#include "Encoder_F.h"

#pragma DATA_SEG Encoder_F_DATA        /* Select data segment "Encoder_F_DATA" */
#pragma CODE_SEG Encoder_F_CODE

/*
** ===================================================================
**     Method      :  Encoder_F_Enable (component PulseAccumulator)
**
**     Description :
**         Enables the component.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte Encoder_F_Enable(void)
{
  /* ECT_PACTL: PAEN=1 */
  setReg8Bits(ECT_PACTL, 0x40U);       /* Enable 16-bit pulse accumulator */ 
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Encoder_F_Disable (component PulseAccumulator)
**
**     Description :
**         Disables the component.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte Encoder_F_Disable(void)
{
  /* ECT_PACTL: PAEN=0 */
  clrReg8Bits(ECT_PACTL, 0x40U);       /* Disable 16-bit pulse accumulator */ 
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Encoder_F_ResetCounter (component PulseAccumulator)
**
**     Description :
**         This method resets the pulse accumulator counter (sets to
**         zero).
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Encoder_F_ResetCounter(void)

**      This method is implemented as macro. See Encoder_F.h file.      **
*/

/*
** ===================================================================
**     Method      :  Encoder_F_GetCounterValue (component PulseAccumulator)
**
**     Description :
**         This method returns the content of the pulse accumulator
**         counter.
**     Parameters  : None
**     Returns     :
**         ---             - Content of the counter register.
** ===================================================================
*/
/*
Encoder_F_TCounterValue Encoder_F_GetCounterValue(void)

**      This method is implemented as macro. See Encoder_F.h file.      **
*/

/*
** ===================================================================
**     Method      :  Encoder_F_Init (component PulseAccumulator)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Encoder_F_Init(void)
{
  /* ECT_PACTL: ??=0,PAEN=1,PAMOD=0,PEDGE=1,CLK1=0,CLK0=0,PAOVI=0,PAI=0 */
  setReg8(ECT_PACTL, 0x50U);           /* Set up pulse accumulator mode */ 
}

/* END Encoder_F. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
