/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ExtInt_Rising.h
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.20, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Vporth
**         User handling procedure     : ExtInt_Rising_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       52            |  PH0_KWH0_MISO1_RxD6
**             ----------------------------------------------------
**
**         Port name                   : H
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Signal edge/level           : rising
**         Priority                    : 4
**         Pull option                 : off
**         Initial state               : Enabled
**
**         Edge register               : PPSH      [$0265]
**         Enable register             : PIEH      [$0266]
**         Request register            : PIFH      [$0267]
**
**         Port data register          : PTH       [$0260]
**         Port control register       : DDRH      [$0262]
**     Contents  :
**         Enable  - void ExtInt_Rising_Enable(void);
**         Disable - void ExtInt_Rising_Disable(void);
**         GetVal  - bool ExtInt_Rising_GetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __ExtInt_Rising_H
#define __ExtInt_Rising_H

/* MODULE ExtInt_Rising. */

/*Including shared modules, which are used in the whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"

#pragma CODE_SEG ExtInt_Rising_CODE


void ExtInt_Rising_Enable(void);
/*
** ===================================================================
**     Method      :  ExtInt_Rising_Enable (component ExtInt)
**
**     Description :
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ExtInt_Rising_Disable() (PIEH_PIEH0 = 0U) /* Disable interrupt "Vporth" */
/*
** ===================================================================
**     Method      :  ExtInt_Rising_Disable (component ExtInt)
**
**     Description :
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ExtInt_Rising_GetVal() (PTH & 0x01U)
/*
** ===================================================================
**     Method      :  ExtInt_Rising_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the component.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/



#pragma CODE_SEG DEFAULT

/* END ExtInt_Rising. */

#endif /* __ExtInt_Rising_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
