/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Control_Timer.c
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : TimerInt
**     Version   : Component 02.159, Driver 01.20, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TIM_Counter (16-bit)
**         Compare name                : TIMTC0
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 8000000 Hz
**           Initial period/frequency
**             Xtal ticks              : 32000
**             microseconds            : 8000
**             milliseconds            : 8
**             seconds (real)          : 0.008
**             Hz                      : 125
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TIM_TCNT  [$03D4]
**              Mode                   : TIM_TIOS  [$03D0]
**              Run                    : TIM_TSCR1 [$03D6]
**              Prescaler              : TIM_TSCR2 [$03DD]
**
**         Compare registers
**              Compare                : TIM_TC0   [$03E0]
**
**         Flip-flop registers
**              Mode                   : TIM_TCTL2 [$03D9]
**     Contents  :
**         Enable       - byte Control_Timer_Enable(void);
**         Disable      - byte Control_Timer_Disable(void);
**         EnableEvent  - byte Control_Timer_EnableEvent(void);
**         DisableEvent - byte Control_Timer_DisableEvent(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Control_Timer. */

#include "Events.h"
#include "Control_Timer.h"

#pragma DATA_SEG Control_Timer_DATA    /* Select data segment "Control_Timer_DATA" */
#pragma CODE_SEG Control_Timer_CODE
#pragma CONST_SEG DEFAULT              /* Use default segment for constants */

volatile bool Control_Timer_EnEvent;   /* Enable/Disable events */


/* Internal method prototypes */


/* End of Internal methods declarations */

/*
** ===================================================================
**     Method      :  Control_Timer_Enable (component TimerInt)
**
**     Description :
**         This method enables the component - it starts the timer.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte Control_Timer_Enable(void)
{
  TIM_TIE_C0I = 1U;                    /* Enable interrupt */ 
  TIM_TSCR1_TEN = 1U;                  /* Start timer */ 
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Control_Timer_Disable (component TimerInt)
**
**     Description :
**         This method disables the component - it stops the timer. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte Control_Timer_Disable(void)
{
  TIM_TIE_C0I = 0U;                    /* Disable interrupt */ 
  TIM_TFLG1 = 0x01U;                   /* Reset interrupt request flag */ 
  TIM_TSCR1_TEN = 0U;                  /* Stop timer */ 
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Control_Timer_EnableEvent (component TimerInt)
**
**     Description :
**         This method enables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte Control_Timer_EnableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  Control_Timer_DisableEvent (component TimerInt)
**
**     Description :
**         This method disables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte Control_Timer_DisableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  Control_Timer_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(Control_Timer_Interrupt)
{
  TIM_TFLG1 = 0x01U;                   /* Reset interrupt request flag */
  if (Control_Timer_EnEvent) {         /* Are the events enabled? */
    Control_Timer_OnInterrupt();       /* Invoke user event */
  }
}

#pragma CODE_SEG Control_Timer_CODE

/* END Control_Timer. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
