/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : MC9S12XEP100_112
**     Version   : Component 01.003, Driver 02.06, CPU db: 3.00.033
**     Datasheet : MC9S12XEP100 Rev. 1.19 12/2008
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "MC9S12XEP100_112" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "LEDs.h"
#include "Switchs.h"
#include "ExtInt_Rising.h"
#include "ExtInt_Falling.h"
#include "IR_Emitter.h"
#include "ADConv.h"
#include "Control_Timer.h"
#include "Encoder_F.h"
#include "DC_F.h"
#include "DC_B.h"
#include "Servo.h"
#include "Encoder_Direction.h"
#include "DC_Direction_F.h"
#include "DC_Direction_B.h"
#include "LCDport.h"
#include "SevenSEG_Data.h"
#include "SevenSEG_Signal.h"
#include "US_echo_timer.h"
#include "US0_echo.h"
#include "US0_trigger.h"
#include "US1_echo.h"
#include "US1_trigger.h"
#include "Encoder_B.h"
#include "US2_echo.h"
#include "US2_trigger.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  0x07FFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12XEP100_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12XEP100_112)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of entry code in a function */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
#pragma MESSAGE DISABLE C5703          /*Disable C5703: Parameter ‘<Parameter>’ declared in function ‘<Function>’ but not referenced */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 13 cycles */
  /* ldd:  2 cycles overhead (load parameter into register) */
  /* jsr:  4 cycles overhead (call this function) */
  /* rts:  7 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 13 cycles */
  /* dbne:  3 cycles overhead (return from this function) */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
    /*
     * Delay
     *   - requested                  : 100 us @ 16MHz,
     *   - possible                   : 1600 c, 100000 ns
     *   - without removable overhead : 1597 c, 99812.5 ns
     */
    pshd                               /* (2 c: 125 ns) backup D */
    ldd #$0212                         /* (2 c: 125 ns) number of iterations */
    label0:
    dbne d, label0                     /* (3 c: 187.5 ns) repeat 530x */
    puld                               /* (3 c: 187.5 ns) restore D */
    /* 100 us delay block end */
    dbne d, loop                       /* us100 parameter is passed via D register */
    rts                                /* return from subroutine */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu__ivVporth (component MC9S12XEP100_112)
**
**     Description :
**         The method services the ivVporth interrupt, which is shared by 
**         several components.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(Cpu__ivVporth)
{
  if (PIFH_PIFH0 != 0U) {              /* Is the device enabled and an interrupt flag is set? */
    if (PIEH_PIEH0 != 0U) {
      PIFH = PIFH_PIFH0_MASK;          /* If yes then clear an interrupt flag */
      ExtInt_Rising_OnInterrupt();
    }
  }
  if (PIFH_PIFH1 != 0U) {              /* Is the device enabled and an interrupt flag is set? */
    if (PIEH_PIEH1 != 0U) {
      PIFH = PIFH_PIFH1_MASK;          /* If yes then clear an interrupt flag */
      ExtInt_Falling_OnInterrupt();
    }
  }
}

#pragma CODE_SEG DEFAULT
/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12XEP100_112)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12XEP100_112)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12XEP100_112)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12XEP100_112)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

#pragma OPTION ADD "-Onf"              /* Disable 'Create Sub-Functions with Common Code optimalization' */
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12XEP100_112)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name            Description */
  setReg8(INT_CFADDR, 0x50U);           
  setReg8(INT_CFDATA2, 0x04U);         /*  0x2A  0xFF54   4   no   ivVtimch0       used by PE */ 
  setReg8(INT_CFADDR, 0x70U);           
  setReg8(INT_CFDATA4, 0x04U);         /*  0x3C  0xFF78   4   no   ivVpit1         used by PE */ 
  setReg8(INT_CFADDR, 0xC0U);           
  setReg8(INT_CFDATA6, 0x04U);         /*  0x66  0xFFCC   4   no   ivVporth        used by PE */ 
  setReg8(INT_CFADDR, 0xD0U);           
  setReg8(INT_CFDATA1, 0x04U);         /*  0x69  0xFFD2   4   no   ivVatd0         used by PE */ 
  /* Initialization of Memory Protection unit */
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=1 */
  setReg8(MPUSEL, 0x01U);              /* Select Descriptor num. 1 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=2 */
  setReg8(MPUSEL, 0x02U);              /* Select Descriptor num. 2 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=3 */
  setReg8(MPUSEL, 0x03U);              /* Select Descriptor num. 3 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=4 */
  setReg8(MPUSEL, 0x04U);              /* Select Descriptor num. 4 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=5 */
  setReg8(MPUSEL, 0x05U);              /* Select Descriptor num. 5 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=6 */
  setReg8(MPUSEL, 0x06U);              /* Select Descriptor num. 6 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=7 */
  setReg8(MPUSEL, 0x07U);              /* Select Descriptor num. 7 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=0 */
  setReg8(MPUSEL, 0x00U);              /* Select Descriptor num. 0 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=1,MSTR1=1,MSTR2=1,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0xE0U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* Common initialization of the CPU registers */
  /* PTM: PTM7=0,PTM6=0,PTM4=0,PTM3=0,PTM2=0,PTM1=0,PTM0=0 */
  clrReg8Bits(PTM, 0xDFU);              
  /* WOMM: WOMM7=0,WOMM6=0,WOMM4=0,WOMM3=0,WOMM2=0,WOMM1=0,WOMM0=0 */
  clrReg8Bits(WOMM, 0xDFU);             
  /* DDRM: DDRM7=1,DDRM6=1,DDRM4=1,DDRM3=1,DDRM2=1,DDRM1=1,DDRM0=1 */
  setReg8Bits(DDRM, 0xDFU);             
  /* PUCR: PUPKE=0,PUPBE=0,PUPAE=0 */
  clrReg8Bits(PUCR, 0x83U);             
  /* DDRK: DDRK3=0,DDRK2=0,DDRK1=0,DDRK0=0 */
  clrReg8Bits(DDRK, 0x0FU);             
  /* PPSH: PPSH1=0,PPSH0=1 */
  clrSetReg8Bits(PPSH, 0x02U, 0x01U);   
  /* PERH: PERH7=0,PERH6=0,PERH5=0,PERH4=0,PERH3=0,PERH2=0,PERH1=0,PERH0=0 */
  setReg8(PERH, 0x00U);                 
  /* PIEH: PIEH7=0,PIEH6=0,PIEH5=0,PIEH4=0,PIEH3=0,PIEH2=0 */
  clrReg8Bits(PIEH, 0xFCU);             
  /* PTH: PTH7=0,PTH5=0,PTH3=0 */
  clrReg8Bits(PTH, 0xA8U);              
  /* DDRH: DDRH7=1,DDRH6=0,DDRH5=1,DDRH4=0,DDRH3=1,DDRH2=0,DDRH1=0,DDRH0=0 */
  setReg8(DDRH, 0xA8U);                 
  /* PWME: PWME7=0,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  setReg8(PWME, 0x00U);                 
  /* PWMCTL: CON45=0,CON01=0,PSWAI=0,PFRZ=0 */
  clrReg8Bits(PWMCTL, 0x5CU);           
  /* PWMCAE: CAE5=0,CAE4=0,CAE1=0,CAE0=0 */
  clrReg8Bits(PWMCAE, 0x33U);           
  /* PWMPOL: PPOL5=1,PPOL4=1,PPOL1=1,PPOL0=1 */
  setReg8Bits(PWMPOL, 0x33U);           
  /* PTP: PTP5=1,PTP4=1,PTP1=1,PTP0=1 */
  setReg8Bits(PTP, 0x33U);              
  /* DDRP: DDRP5=1,DDRP4=1,DDRP1=1,DDRP0=1 */
  setReg8Bits(DDRP, 0x33U);             
  /* TIM_TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=1,??=0,??=0,??=0 */
  setReg8(TIM_TSCR1, 0x08U);            
  /* TIM_OCPD: OCPD7=1,OCPD6=1,OCPD5=1,OCPD4=1,OCPD3=1,OCPD2=1,OCPD1=1,OCPD0=1 */
  setReg8(TIM_OCPD, 0xFFU);             
  /* TIM_PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(TIM_PACTL, 0x0CU);        
  /* TIM_OC7M: OC7M0=0 */
  clrReg8Bits(TIM_OC7M, 0x01U);         
  /* TIM_TIOS: IOS7=1,IOS0=1 */
  setReg8Bits(TIM_TIOS, 0x81U);         
  /* TIM_TCTL2: OM0=0,OL0=0 */
  clrReg8Bits(TIM_TCTL2, 0x03U);        
  /* TIM_TTOV: TOV7=0,TOV0=0 */
  clrReg8Bits(TIM_TTOV, 0x81U);         
  /* TIM_TCTL1: OM7=0,OL7=0 */
  clrReg8Bits(TIM_TCTL1, 0xC0U);        
  /* TIM_TSCR2: TOI=0,TCRE=1 */
  clrSetReg8Bits(TIM_TSCR2, 0x80U, 0x08U); 
  /* TIM_TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  setReg8(TIM_TFLG1, 0xFFU);            
  /* TIM_TIE: C0I=1 */
  setReg8Bits(TIM_TIE, 0x01U);          
  /* TIM_PTPSR: PTPS7=0,PTPS6=0,PTPS5=0,PTPS4=0,PTPS3=0,PTPS2=0,PTPS1=0,PTPS0=1 */
  setReg8(TIM_PTPSR, 0x01U);            
  /* ECT_PACTL: PAEN=0 */
  clrReg8Bits(ECT_PACTL, 0x40U);        
  /* ECT_TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(ECT_TSCR1, 0x00U);            
  /* ECT_PBCTL: PBEN=0 */
  clrReg8Bits(ECT_PBCTL, 0x40U);        
  /* ECT_DLYCT: DLY7=0,DLY6=0,DLY5=0,DLY4=0,DLY3=0,DLY2=0,DLY1=0,DLY0=0 */
  setReg8(ECT_DLYCT, 0x00U);            
  /* ECT_ICSYS: SH37=0,SH26=0,SH15=0,SH04=0,PACMX=0,BUFEN=0,LATQ=0 */
  clrReg8Bits(ECT_ICSYS, 0xF7U);        
  /* ECT_ICOVW: NOVW7=1,NOVW0=1 */
  setReg8Bits(ECT_ICOVW, 0x81U);        
  /* ECT_TIOS: IOS7=0,IOS0=0 */
  clrReg8Bits(ECT_TIOS, 0x81U);         
  /* PERT: PERT7=0,PERT0=0 */
  clrReg8Bits(PERT, 0x81U);             
  /* PERS: PERS3=0 */
  clrReg8Bits(PERS, 0x08U);             
  /* PTS: PTS7=1,PTS6=1,PTS5=1,PTS4=1 */
  setReg8Bits(PTS, 0xF0U);              
  /* DDRS: DDRS7=1,DDRS6=1,DDRS5=1,DDRS4=1,DDRS3=0 */
  clrSetReg8Bits(DDRS, 0x08U, 0xF0U);   
  /* PORTB: PB7=0,PB6=0,PB5=0,PB4=0,PB3=0,PB2=0,PB1=0,PB0=0 */
  setReg8(PORTB, 0x00U);                
  /* DDRB: DDRB7=1,DDRB6=1,DDRB5=1,DDRB4=1,DDRB3=1,DDRB2=1,DDRB1=1,DDRB0=1 */
  setReg8(DDRB, 0xFFU);                 
  /* PORTA: PA7=0,PA6=0,PA5=0,PA4=0,PA3=0,PA2=0,PA1=0,PA0=0 */
  setReg8(PORTA, 0x00U);                
  /* DDRA: DDRA7=1,DDRA6=1,DDRA5=1,DDRA4=1,DDRA3=1,DDRA2=1,DDRA1=1,DDRA0=1 */
  setReg8(DDRA, 0xFFU);                 
  /* WOMS: WOMS7=0,WOMS6=0,WOMS5=0,WOMS4=0 */
  clrReg8Bits(WOMS, 0xF0U);             
  /* PITCFLMT: PITE=0 */
  clrReg8Bits(PITCFLMT, 0x80U);         
  /* PITCE: PCE1=0 */
  clrReg8Bits(PITCE, 0x02U);            
  /* PITTF: PTF1=1 */
  setReg8Bits(PITTF, 0x02U);            
  /* PITINTE: PINTE1=1 */
  setReg8Bits(PITINTE, 0x02U);          
  /* PITMTLD1: PMTLD7=0,PMTLD6=0,PMTLD5=0,PMTLD4=0,PMTLD3=0,PMTLD2=0,PMTLD1=0,PMTLD0=0 */
  setReg8(PITMTLD1, 0x00U);             
  /* PITMUX: PMUX1=1 */
  setReg8Bits(PITMUX, 0x02U);           
  /* ECT_TCTL4: EDG0B=0,EDG0A=1 */
  clrSetReg8Bits(ECT_TCTL4, 0x02U, 0x01U); 
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* VREGCTRL: LVIE=0 */
  clrReg8Bits(VREGCTRL, 0x02U);         
  /* COPCTL: WCOP=0,RSBCK=0,WRTMASK=0,??=0,??=0,CR2=0,CR1=0,CR0=0 */
  setReg8(COPCTL, 0x00U);               
  /* RDRIV: RDPK=0,RDPE=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 0x93U);            
  /* RDRH: RDRH7=0,RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  setReg8(RDRH, 0x00U);                 
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 0xC3U);             
  /* RDRM: RDRM7=0,RDRM6=0,RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  setReg8(RDRM, 0x00U);                 
  /* RDRP: RDRP7=0,RDRP6=0,RDRP5=0,RDRP4=0,RDRP3=0,RDRP2=0,RDRP1=0,RDRP0=0 */
  setReg8(RDRP, 0x00U);                 
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0x00U);                 
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  setReg8(RDRT, 0x00U);                 
  /* RDR0AD0: RDR0AD07=0,RDR0AD06=0,RDR0AD05=0,RDR0AD04=0,RDR0AD03=0,RDR0AD02=0,RDR0AD01=0,RDR0AD00=0 */
  setReg8(RDR0AD0, 0x00U);              
  /* RDR1AD0: RDR1AD07=0,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  setReg8(RDR1AD0, 0x00U);              
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 0x40U);            
  /* ATD0DIEN: IEN7=0,IEN6=0,IEN5=0,IEN4=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  clrReg16Bits(ATD0DIEN, 0xFFU);        
  /* ECT_PACN32: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_PACN32, 0x00U);          
  /* ECT_PACN10: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(ECT_PACN10, 0x00U);          
  /* ### MC9S12XEP100_112 "Cpu" init code ... */
  /* ### BitsIO "LEDs" init code ... */
  /* ### BitsIO "Switchs" init code ... */
  /* ### External interrupt "ExtInt_Rising" init code ... */
  PIFH = 0x01U;                         /* Clear flag */
  PIEH_PIEH0 = 1U;                     /* Enable interrupt */
  /* ### External interrupt "ExtInt_Falling" init code ... */
  PIFH = 0x02U;                         /* Clear flag */
  PIEH_PIEH1 = 1U;                     /* Enable interrupt */
  /* ### Programable pulse generation "IR_Emitter" init code ... */
  IR_Emitter_Init();
  /* ###  "ADConv" init code ... */
  ADConv_Init();
  /* ### TimerInt "Control_Timer" init code ... */
  /* TIM_TC0: BIT15=1,BIT14=1,BIT13=1,BIT12=1,BIT11=1,BIT10=0,BIT9=1,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(TIM_TC0, 0xFA00U);          /* Store given value to the compare register */ 
  /* TIM_TC7: BIT15=1,BIT14=1,BIT13=1,BIT12=1,BIT11=1,BIT10=0,BIT9=1,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(TIM_TC7, 0xFA00U);          /* Store given value to the modulo register */ 
  Control_Timer_EnEvent = TRUE;        /* Enable events */
  /* ### PulseAccumulator "Encoder_F" init code ... */
  Encoder_F_Init();
  /* ### Programable pulse generation "DC_F" init code ... */
  DC_F_Init();
  /* ### Programable pulse generation "DC_B" init code ... */
  DC_B_Init();
  /* ### Programable pulse generation "Servo" init code ... */
  Servo_Init();
  /* ### BitIO "Encoder_Direction" init code ... */
  /* ### BitIO "DC_Direction_F" init code ... */
  /* ### BitIO "DC_Direction_B" init code ... */
  /* ### ByteIO "LCDport" init code ... */
  /* ### ByteIO "SevenSEG_Data" init code ... */
  /* ### BitsIO "SevenSEG_Signal" init code ... */
  /* ### TimerInt "US_echo_timer" init code ... */
  /* PITLD1: PLD15=0,PLD14=0,PLD13=0,PLD12=0,PLD11=0,PLD10=0,PLD9=0,PLD8=0,PLD7=1,PLD6=0,PLD5=1,PLD4=0,PLD3=0,PLD2=0,PLD1=0,PLD0=0 */
  setReg16(PITLD1, 0xA0U);             /* Store given value to the compare register */ 
  /* PITCE: PCE1=1 */
  setReg8Bits(PITCE, 0x02U);           /* Enable Timer */ 
  US_echo_timer_EnEvent = TRUE;        /* Enable events */
  /* ### BitIO "US0_echo" init code ... */
  /* ### BitIO "US0_trigger" init code ... */
  /* ### BitIO "US1_echo" init code ... */
  /* ### BitIO "US1_trigger" init code ... */
  /* ### PulseAccumulator "Encoder_B" init code ... */
  Encoder_B_Init();
  /* ### BitIO "US2_echo" init code ... */
  /* ### BitIO "US2_trigger" init code ... */
  /* Common peripheral initialization - ENABLE */
  /* TIM_TSCR1: TEN=1,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(TIM_TSCR1, 0x80U);            
  /* PITCFLMT: PITE=1 */
  setReg8Bits(PITCFLMT, 0x80U);         
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm {
    PSHA
    LDAA #0
    TFR A,CCRH
    PULA
  }
  /*lint -restore Enable MISRA rule (1.1) checking. */
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

#pragma CODE_SEG __NEAR_SEG NON_BANKED

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12XEP100_112)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma OPTION ADD "-Onf"              /* 'Create Sub-Functions with Common Code optimalization' must be disabled because stack is not yet initialized */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{
  /* ### MC9S12XEP100_112 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* MMCCTL1: TGMRAMON=0,??=0,EEEIFRON=0,PGMIFRON=0,RAMHM=0,EROMON=0,ROMHM=0,ROMON=1 */
  setReg8(MMCCTL1, 0x01U);              
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  setReg8(DIRECT, 0x00U);               
  /* IVBR: IVB_ADDR=0xFF */
  setReg8(IVBR, 0xFFU);                 
  /* ECLKCTL: NECLK=1,NCLKX2=1,DIV16=0,EDIV4=0,EDIV3=0,EDIV2=0,EDIV1=0,EDIV0=0 */
  setReg8(ECLKCTL, 0xC0U);              
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,XCLKS=0,??=0,PLLWAI=0,??=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0x81U);              /* Disable the PLL */ 
  /* SYNR: VCOFRQ1=0,VCOFRQ0=0,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=0,SYNDIV1=1,SYNDIV0=1 */
  setReg8(SYNR, 0x03U);                /* Set the multiplier register */ 
  /* REFDV: REFFRQ1=0,REFFRQ0=1,REFDIV5=0,REFDIV4=0,REFDIV3=0,REFDIV2=0,REFDIV1=0,REFDIV0=0 */
  setReg8(REFDV, 0x40U);               /* Set the divider register */ 
  /* POSTDIV: ??=0,??=0,??=0,POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  setReg8(POSTDIV, 0x00U);             /* Set the post divider register */ 
  /* PLLCTL: CME=1,PLLON=1,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xC1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /* VREGHTCL: ??=0,??=0,VSEL=0,VAE=1,HTEN=0,HTDS=0,HTIE=0,HTIF=0 */
  setReg8(VREGHTCL, 0x10U);             
  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
