/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LEDs.h
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.13, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings  :
**         Port name                   : M
**
**         Bit mask of the port        : $001F
**         Number of bits/pins         : 5
**         Single bit numbers          : 0 to 4
**         Values range                : 0 to 31
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTM       [$0250]
**         Port control register       : DDRM      [$0252]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    105  |   PM0_RxCAN0
**                    1      |    104  |   PM1_TxCAN0
**                    2      |    103  |   PM2_RxCAN1_RxCAN0_MISO0
**                    3      |    102  |   PM3_TxCAN1_TxCAN0_SS0
**                    4      |    101  |   PM4_RxCAN2_RxCAN0_RxCAN4_MOSI0
**             ----------------------------------------------------
**
**         Optimization for            : code size
**     Contents  :
**         GetDir - bool LEDs_GetDir(void);
**         GetVal - byte LEDs_GetVal(void);
**         PutVal - void LEDs_PutVal(byte Val);
**         GetBit - bool LEDs_GetBit(byte Bit);
**         PutBit - void LEDs_PutBit(byte Bit, bool Val);
**         SetBit - void LEDs_SetBit(byte Bit);
**         ClrBit - void LEDs_ClrBit(byte Bit);
**         NegBit - void LEDs_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef LEDs_H_
#define LEDs_H_

/* MODULE LEDs. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG LEDs_CODE
/*
** ===================================================================
**     Method      :  LEDs_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 31)
** ===================================================================
*/
byte LEDs_GetVal(void);

/*
** ===================================================================
**     Method      :  LEDs_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_PutVal(byte Val);

/*
** ===================================================================
**     Method      :  LEDs_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 4)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool LEDs_GetBit(byte Bit);

/*
** ===================================================================
**     Method      :  LEDs_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 4)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_PutBit(byte Bit, bool Val);

/*
** ===================================================================
**     Method      :  LEDs_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 4)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_ClrBit(byte Bit);

/*
** ===================================================================
**     Method      :  LEDs_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 4)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_SetBit(byte Bit);

/*
** ===================================================================
**     Method      :  LEDs_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void LEDs_NegBit(byte Bit);

/*
** ===================================================================
**     Method      :  LEDs_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
#define LEDs_GetDir() ( \
    (bool)1U                           /* Pins are fixed to GPO mode */ \
  )

#pragma CODE_SEG DEFAULT

/* END LEDs. */
#endif /* #ifndef __LEDs_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
