/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SevenSEG_Data.c
**     Project   : SCC_02
**     Processor : MC9S12XEP100CAL
**     Component : ByteIO
**     Version   : Component 02.058, Driver 03.15, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2012-07-15, ¿ÀÀü 12:00
**     Abstract  :
**         This component "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : A
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         8-bit data register         : PORTA     [$0000]
**         8-bit control register      : DDRA      [$0002]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    57   |   PA0
**                    1      |    58   |   PA1
**                    2      |    59   |   PA2
**                    3      |    60   |   PA3
**                    4      |    61   |   PA4
**                    5      |    62   |   PA5
**                    6      |    63   |   PA6
**                    7      |    64   |   PA7
**             ----------------------------------------------------
**     Contents  :
**         PutVal - void SevenSEG_Data_PutVal(byte Val);
**         NegBit - void SevenSEG_Data_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE SevenSEG_Data. */

#include "SevenSEG_Data.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu.h"

#pragma DATA_SEG SevenSEG_Data_DATA    /* Select data segment "SevenSEG_Data_DATA" */
#pragma CODE_SEG SevenSEG_Data_CODE
#pragma CONST_SEG SevenSEG_Data_CONST  /* Constant section for this module */
/*
** ===================================================================
**     Method      :  SevenSEG_Data_GetMsk (component ByteIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte SevenSEG_Data_Table[8U] = {
  0x01U, 0x02U, 0x04U, 0x08U, 0x10U, 0x20U, 0x40U, 0x80U
};                                     /* Table of mask constants */

static byte SevenSEG_Data_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<8U) ? SevenSEG_Data_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  SevenSEG_Data_PutVal (component ByteIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
/*
void SevenSEG_Data_PutVal(byte Val)

**  This method is implemented as a macro. See SevenSEG_Data.h file.  **
*/

/*
** ===================================================================
**     Method      :  SevenSEG_Data_NegBit (component ByteIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void SevenSEG_Data_NegBit(byte Bit)
{
  byte const Mask = SevenSEG_Data_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PORTA, Mask);         /* [bit Bit]=invert */
}


/* END SevenSEG_Data. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
